---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volterra-ingress-controller
  namespace: sharp-poodle
spec:
  project: default
  source:
    path: charts/volterra-ingress-controller
    repoURL: https://github.com/tomminux/techxchange-gitops-lab.git
    targetRevision: HEAD
  destination:
    namespace: volt-ic
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
